#### import dependencies

In [2]:
import pandas as pd
# import numpy as np
import requests
# import json
# from http import HTTPStatus

#### import needed API keys

In [8]:
from config import yelp_api_key_Austin, yelp_api_key_Shane, yelp_client_id_Shane

#### set csv data file filepaths (for both import & output), then import needed data into data frame and visualize data frame

#### set input CSV data file filepath variable

In [9]:
# dallas_open_data = "../Other/Resources/dal_open_data_2019_inspection_month.csv"
# dallas_open_data = "../Other/Resources/test1.csv"
dallas_open_data = "../Other/Resources/full_test_1.csv"

#### set output CSV data file & png image file filepath variable

In [11]:
output_data_filepath = "output_data/"

#### import Dallas Open Data CSV data file (with lat/lng added; obtained from Google API) into dataframe & visualize data frame

In [12]:
dallas_open_data_df = pd.read_csv(dallas_open_data, dtype="object", encoding="utf-8")

dallas_open_data_df.head()

,restaurant_name,inspection_type,inspection_date,inspection_score,street_number,street_name,street_unit,zip_code,street_address,inspection_month,inspection_year,lat,long,Unique Join
0,2204,Routine,43644,95,2204,ELM,NaN,75201,3922 SIMPSON ST,43617,FY2019,39.811585,-94.834959,NaN
1,13209,Routine,43684,96,13209,C F HAWN,NaN,75253,1910 S HARWOOD ST,43678,FY2019,32.6775,-96.604348,NaN
2,44023,Routine,43817,80,1102,KIEST,NaN,75224,1201 ELM ST #LL09,43800,FY2020,32.705756,-96.840532,NaN
3,"""LET'S DO LUNCH""",Routine,43705,100,1720,REGAL,#105,75235,2704 ELM ST,43678,FY2019,32.836816,-96.872095,NaN
4,1-STOP SHOP,Routine,43804,91,1512,BELTLINE,#2,75253,238 W ILLINOIS AVE,43800,FY2020,32.681431,-96.595947,NaN

#### create a second data frame to use below and visualize the data frame

In [88]:
df = dallas_open_data_df.head(50)
df

,restaurant_name,inspection_type,inspection_date,inspection_score,street_number,street_name,street_unit,zip_code,street_address,inspection_month,inspection_year,lat,long,Unique Join
0,2204,Routine,43644,95,2204,ELM,NaN,75201,3922 SIMPSON ST,43617,FY2019,39.811585,-94.834959,NaN
1,13209,Routine,43684,96,13209,C F HAWN,NaN,75253,1910 S HARWOOD ST,43678,FY2019,32.6775,-96.604348,NaN
2,44023,Routine,43817,80,1102,KIEST,NaN,75224,1201 ELM ST #LL09,43800,FY2020,32.705756,-96.840532,NaN
3,"""LET'S DO LUNCH""",Routine,43705,100,1720,REGAL,#105,75235,2704 ELM ST,43678,FY2019,32.836816,-96.872095,NaN
4,1-STOP SHOP,Routine,43804,91,1512,BELTLINE,#2,75253,238 W ILLINOIS AVE,43800,FY2020,32.681431,-96.595947,NaN
5,12 CUTS STEAK HOUSE,Routine,43768,91,18010,DALLAS,NaN,75287,2821 GREENVILLE AVE,43739,FY2020,32.99597,-96.829032,NaN
6,13910 SHELL,Routine,43801,96,13910,CENTRAL,NaN,75243,214 N AKARD ST,43800,FY2020,32.937077,-96.748821,NaN
7,15695 HEIGHTS PREP,Routine,43760,91,2806,CANADA,NaN,75212,6610 LAKE JUNE RD,43739,FY2020,32.792643,-96.866047,NaN
8,15710 FOODA-CHASE TOWER,Routine,43614,96,2200,ROSS,NaN,75201,3818 W ILLINOIS AVE,43586,FY2019,33.655467,-84.461266,NaN
9,15734 3D CANTINA,Routine,43769,82,2707,MLK,#130,75215,6057 SKILLMAN ST,43739,FY2020,0,0,NaN
10,15742 TEXAS FOOD MART,Routine,43665,82,2984,WHEATLAND,#E,75037,7812 GREAT TRINITY FOREST WAY #300,43647,FY2019,32.647456,-96.869413,NaN
11,15757 JAZEN TEA,Routine,43472,96,11613,CENTRAL,#106A,75243,14010 COIT RD,43466,FY2019,32.906744,-96.769361,NaN
12,15789 THE MERCHANT AT LOWER GREENVILLE,Routine,43630,96,1924,GREENVILLE,NaN,75206,3206 W DAVIS ST #B,43617,FY2019,37.532278,-77.471571,NaN
13,15805 DOTTEA,Routine,43816,93,14902,PRESTON,#500,75254,2324 W CLARENDON DR,43800,FY2020,32.951326,-96.803474,NaN
14,1600 CAFE,Routine,43790,94,1600,VICEROY,#125,75235,2500 VICTORY AVE PLZA #1027,43770,FY2020,32.834702,-96.869462,NaN
15,"16096 TRINITY BASIN PREPARATORY, INC",Routine,43746,100,2524,LEDBETTER,BU4,75237,5365 SPRING VALLEY RD #101,43739,FY2020,32.691159,-96.859592,NaN
16,16152 VIDORRA,Routine,43605,84,2642,MAIN,#100,75226,5956 SHERRY LN #1700,43586,FY2019,41.678741,-70.026921,NaN
17,16159 CORELOGIC MICROMARKET,Routine,43531,100,3001,HACKBERRY,NaN,75063,7995 LBJ STE #118,43525,FY2019,35.6015,-97.572176,NaN
18,16161 AH BELO DALLAS MORNING NEWS MICROMARKET,Routine,43490,99,1954,COMMERCE,NaN,75201,325 N SAINT PAUL ST #P5,43466,FY2019,32.780922,-96.794296,NaN
19,16162 - KPMG,Routine,43640,95,2323,ROSS,NaN,75201,4302 BRYAN ST,43617,FY2019,32.787783,-97.354094,NaN
20,1717 RESTAURANT,Routine,43738,91,1717,HARWOOD,NaN,75201,2660 ROBERT B CULLUM BLVD,43709,FY2019,32.787754,-96.8002,NaN
21,20 FEET,Routine,43706,97,1160,PEAVY,NaN,75218,1400 HI LINE DR #120,43678,FY2019,42.588967,-83.942927,NaN
22,2100 DELI,Routine,43644,80,2100,MCKINNEY,#150,75201,3520 GREENVILLE AVE,43617,FY2019,32.791859,-96.803195,NaN
23,2817 MAPLE LLC,Routine,43727,86,2817,MAPLE,#210,75201,6887 SHADY BROOK LN,43709,FY2019,40.501132,-78.416087,NaN
24,3 FORKS RESTAURANT,Routine,43703,88,17776,DALLAS,NaN,75287,2800 ROUTH ST #170,43678,FY2019,32.991679,-96.828962,NaN
25,3015 AT TRINITY GROVES,Routine,43823,98,3015,GULDEN,#100,75212,8055 S LOOP 12,43800,FY2020,32.779272,-96.827706,NaN
26,303 BAR & GRILL,Routine,43826,97,303,DAVIS,NaN,75208,8112 S HAMPTON RD,43800,FY2020,42.640152,-92.054562,NaN
27,303 BAR & GRILL (BAR AREA),Routine,43782,94,303,DAVIS,NaN,75208,8120 W CAMP WISDOM RD FLR 1,43770,FY2020,33.302557,-96.40284,NaN
28,3131 LOUNGE,Routine,43738,100,3131,MAIN,NaN,75219,8687 N CENTRAL EXPW,43709,FY2019,40.556674,-75.288257,NaN
29,3ELEVEN KITCHEN & COCKTAILS,Routine,43776,88,311,MARKET,#100,75202,8390 N STEMMONS FRWY #B,43770,FY2020,32.781443,-96.80673,NaN
30,4 SEASONS FOOD MART,Routine,43752,85,19090,MARSH,NaN,75287,3102 OAK LAWN AVE #110,43739,FY2020,33.011386,-96.857189,NaN
31,45 MINT,Routine,43698,97,14902,PRESTON,#512B,75254,2326 N HENDERSON AVE,43678,FY2019,32.951326,-96.803474,NaN
32,5 STAR CHEVRON,Routine,43517,90,3301,FORT WORTH,NaN,75211,9222 JOHN W. CARPENTER FRWY,43497,FY2019,32.753338,-96.874373,NaN
33,50286 SLAYTER'S 50/50 UPSTAIRS BAR (2ND FL),Routine,43511,100,2817,GREENVILLE,NaN,75206,6867 GREENVILLE AVE,43497,FY2019,32.822958,-96.770158,NaN
34,6-TWELVE FOOD STORE,Routine,43555,93,1221,HAMPTON,NaN,75208,1722 ROUTH ST STE #110,43525,FY2019,32.76083,-96.856752,NaN
35,6-TWELVE FOOD STORE #102,Routine,43776,80,1910,EDGEFIELD,NaN,75224,3105 W DAVIS ST,43770,FY2020,32.726369,-96.84461,NaN
36,7 - ELEVEN #35421,Routine,43753,93,10804,PRESTON,NaN,75230,116 W JEFFERSON BLVD,43739,FY2020,32.895179,-96.803854,NaN
37,7- ELEVEN CONVENIENCE STORE #21368C,Routine,43727,94,2120,GREENVILLE,NaN,75206,3636 FRANKFORD RD 390,43709,FY2019,38.064016,-79.111132,NaN
38,7-11 #18765,Routine,43777,83,111,CARROLL,NaN,75226,12107 ABRAMS RD,43770,FY2020,32.791767,-96.76778,NaN
39,7-11 #25080,Routine,43467,98,17605,MIDWAY,NaN,75252,2741 N STEMMONS FRWY,43466,FY2019,32.987624,-96.842217,NaN
40,7-11 #26151,Routine,43637,80,1410,ILLINOIS,NaN,75216,2222 FORT WORTH AVE #160,43617,FY2019,32.720022,-96.80427,NaN
41,7-11 #27529,Routine,43745,98,18101,COIT,NaN,75252,2838 W DAVIS ST,43739,FY2020,32.997999,-96.7679,NaN
42,7-11CONVENIENCE STORE #33441,Routine,43542,98,2608,ELM,NaN,75226,5601 SEARS ST,43525,FY2019,41.927221,-87.851575,NaN
43,7-ELEVEN,Routine,43808,89,3230,DAVIS,NaN,75211,909 N WASHINGTON AVE,43800,FY2020,32.749487,-96.873869,NaN
44,7-ELEVEN #12200,Routine,43746,93,2529,OAK LAWN,NaN,75219,5410 LBJ FRWY,43739,FY2020,32.804923,-96.813435,NaN
45,7-ELEVEN #18717,Routine,43759,80,2223,BECKLEY,NaN,75224,4023 LEMMON AVE,43739,FY2020,32.720697,-96.82287,NaN
46,7-ELEVEN #20769,Routine,43508,86,10340,FOREST,#106,75243,10788 HARRY HINES BLVD E28,43497,FY2019,32.909001,-96.708075,NaN
47,7-ELEVEN #26771C,Routine,43488,91,18118,MIDWAY,NaN,75252,2911 LOMBARDY LN #101,43466,FY2019,32.996971,-96.843771,NaN
48,7-ELEVEN #27206,Routine,43522,91,13601,C F HAWN,NaN,75253,2115 BUTLER ST,43497,FY2019,32.676281,-96.601555,NaN
49,7-ELEVEN #34102,Routine,43475,84,2061,FORT WORTH,NaN,75208,3500 GOLDMAN ST,43466,FY2019,32.76258,-96.855964,NaN

#### set blank restaurant search variables that will be used in API request

In [89]:
search_name = ""
search_address = ""
search_street_number = ""
search_street_name = ""
search_zip_code = ""
search_lat = ""
search_lng = ""

####  set API URL and API key variables to pass through in the API request

In [90]:
api_key_1 = yelp_api_key_Shane
api_key_2 = yelp_api_key_Austin

headers_1 = {'Authorization': 'Bearer %s' % api_key_1}
headers_2 = {'Authorization': 'Bearer %s' % api_key_2}

url = 'https://api.yelp.com/v3/businesses/search'
#     'https://api.yelp.com/v3/businesses/{id}'

#### create empty lists for the data returned from the API requests; to be placed into the dictionary, then data frame

In [91]:
# create empty lists for the data
# restaurant_categories = []
restaurant_category_test = []
restaurant_category_1 = []
restaurant_category_2 = []
restaurant_category_3 = []
restaurant_latitude = []
restaurant_longitude = []
restaurant_display_phone = []
restaurant_distance = []
restaurant_id = []
restaurant_alias = []
restaurant_image_url = []
restaurant_is_closed = []
restaurant_address1 = []
restaurant_address2 = []
restaurant_address3 = []
restaurant_city = []
restaurant_country = []
restaurant_display_address = []
restaurant_state = []
restaurant_zip_code = []
restaurant_name = []
restaurant_phone = []
restaurant_price = []
restaurant_rating = []
restaurant_review_count = []
restaurant_url = []
restaurant_transactions = []
restaurant_region_center_lat = []
restaurant_region_center_long = []

#### create variable to hold an empty value
##### to be used in above lists when object returned from API request doesn't include that piece of info (needed so all lists are same length and can be turned into a dictionary)

In [92]:
missing_api_result = ""

#### create counter to be used in for loop

In [93]:
counter = 0

#### loop through rows in df, sending an API request for that restaurant using restaurant_name, street_number, street_name and zip_code

In [33]:
# for row in df["restaurant_name"]:
    
#     # get restaurant data from df, setting respective variables for that restaurant
#     search_name = df["restaurant_name"][counter]
#     search_street_number = df["street_number"][counter]
#     search_street_name = df["street_name"][counter]
#     search_zip_code = df["zip_code"][counter]
# #     search_lat = df["lat"][counter]
# #     search_lng = df["long"][counter]
    
#     # set API request parameters
#     params = {
# #         "term": f"restaurant,{search_name}",
# #         "term": f"{search_name}",
#         "term": "steak",
# #         "location": f"{search_street_number} {search_street_name}, {search_zip_code}",
#         "location": "Dallas",
# #         "latitude": xx,
# #         "longitude": xx,
#         "radius": 1000,
# #         "limit": 3,
#         "sort_by": "best_match"
#     }
    
#     # set yelp_response to results from API request
#     yelp_response = requests.get(url, params=params, headers=headers_1).json()
    
#     # traverse json object, set yelp_results to only business data for the best match result (0 index position)
#     try:
#         yelp_results = yelp_response["businesses"][0]
# #     yelp_results = yelp_response["businesses"][0]
# #     yelp_results = yelp_response["businesses"]
#     except:
#         pass
    
#     try:
#         restaurant_category_test.append(yelp_results["categories"][0]["title"])
#     # not all results have > 1 category; in order to create dict, all lists must be same size - must assign "" when there is only one category
#         if len(yelp_results[0]["categories"]) >= 1:
#             restaurant_category_1.append(yelp_results["categories"][0]["title"])
#         else:
#             restaurant_category_1.append(missing_api_result)
#         if len(yelp_results[0]["categories"]) >= 2:
#             restaurant_category_2.append(yelp_results["categories"][1]["title"])
#         else:
#             restaurant_category_2.append(missing_api_result)
#         if len(yelp_results[0]["categories"]) >= 3:
#             restaurant_category_3.append(yelp_results["categories"][2]["title"])
#         else:
#             restaurant_category_3.append(missing_api_result)
#     except:
#         restaurant_category_test.append(missing_api_result)
        
#     try:
#         restaurant_latitude.append(yelp_results["coordinates"]["latitude"])
#     except:
#         restaurant_latitude.append(missing_api_result)
        
#     try:
#         restaurant_longitude.append(yelp_results["coordinates"]["longitude"])
#     except:
#         restaurant_longitude.append(missing_api_result)
        
#     try:
#         restaurant_display_phone.append(yelp_results["display_phone"])
#     except:
#         restaurant_display_phone.append(missing_api_result)
        
#     try:
#         restaurant_distance.append(yelp_results["distance"])
#     except:
#         restaurant_distance.append(missing_api_result)
        
#     try:
#         restaurant_id.append(yelp_results["id"])
#     except:
#         restaurant_id.append(missing_api_result)
        
#     try:
#         restaurant_alias.append(yelp_results["alias"])
#     except:
#         restaurant_alias.append(missing_api_result)
        
#     try:
#         restaurant_image_url.append(yelp_results["image_url"])
#     except:
#         restaurant_image_url.append(missing_api_result)
        
#     try:
#         restaurant_is_closed.append(yelp_results["is_closed"])
#     except:
#         restaurant_is_closed.append(missing_api_result)
        
#     try:
#         restaurant_address1.append(yelp_results["location"]["address1"])
#     except:
#         restaurant_address1.append(missing_api_result)
        
#     try:
#         restaurant_address2.append(yelp_results["location"]["address2"])
#     except:
#         restaurant_address2.append(missing_api_result)
        
#     try:
#         restaurant_address3.append(yelp_results["location"]["address3"])
#     except:
#         restaurant_address3.append(missing_api_result)
        
#     try:
#         restaurant_city.append(yelp_results["location"]["city"])
#     except:
#         restaurant_city.append(missing_api_result)
        
#     try:
#         restaurant_country.append(yelp_results["location"]["country"])
#     except:
#         restaurant_country.append(missing_api_result)
        
#     try:
#         restaurant_display_address.append(yelp_results["location"]["display_address"])
#     except:
#         restaurant_display_address.append(missing_api_result)
        
#     try:
#         restaurant_state.append(yelp_results["location"]["state"])
#     except:
#         restaurant_state.append(missing_api_result)
        
#     try:
#         restaurant_zip_code.append(yelp_results["location"]["zip_code"])
#     except:
#         restaurant_zip_code.append(missing_api_result)
        
#     try:
#         restaurant_name.append(yelp_results["name"])
#     except:
#         restaurant_name.append(missing_api_result)
        
#     try:
#         restaurant_phone.append(yelp_results["phone"])
#     except:
#         restaurant_phone.append(missing_api_result)
        
# #     restaurant_price.append(yelp_results["price"])
#     # not all results have Price; to prevent error, try/except error handling, assigning "", all lists must be same size - must assign "" when there is no Price
#     try:
#         restaurant_price.append(yelp_results["price"])
#     except:
#         restaurant_price.append(missing_api_result)
#     try:
#         restaurant_rating.append(yelp_results["rating"])
#     except:
#         restaurant_rating.append(missing_api_result)
#     try:
#         restaurant_review_count.append(yelp_results["review_count"])
#     except:
#         restaurant_review_count.append(missing_api_result)
#     try:
#         restaurant_url.append(yelp_results["url"])
#     except:
#         restaurant_url.append(missing_api_result)
    
#     counter += 1

In [94]:
# counter = 0

In [95]:
# for row in df["restaurant_name"]:
    
#     # get restaurant data from df, setting respective variables for that restaurant
#     search_name = df["restaurant_name"][counter]
#     search_street_number = df["street_number"][counter]
#     search_street_name = df["street_name"][counter]
#     search_zip_code = df["zip_code"][counter]
# #     search_lat = df["lat"][counter]
# #     search_lng = df["long"][counter]
    
#     # set API request parameters
#     params = {
# #         "term": f"restaurant,{search_name}",
#         "term": f"{search_name}",
#         "location": f"{search_street_number} {search_street_name}, {search_zip_code}",
# #         "location": "Dallas",
# #         "latitude": xx,
# #         "longitude": xx,
#         "radius": 1000,
#         "limit": 3,
#         "sort_by": "best_match"
#     }
    
#     # set yelp_response to results from API request
#     yelp_response = requests.get(url, params=params, headers=headers_1).json()
    
#     # traverse json object, set yelp_results to only business data for the best match result (0 index position)
#     try:
#         yelp_results = yelp_response["businesses"][0]
# #     yelp_results = yelp_response["businesses"][0]
# #     yelp_results = yelp_response["businesses"]

#         # not all results have all fields; to prevent error, try/except error handling, assigning "" (empty value)
#         try:
#             restaurant_category_1.append(yelp_results["categories"][0]["title"])
#         except:
#             restaurant_category_1.append(missing_api_result)
            
#         try:
#             restaurant_category_2.append(yelp_results["categories"][1]["title"])
#         except:
#             restaurant_category_2.append(missing_api_result)
            
#         try:
#             restaurant_category_3.append(yelp_results["categories"][2]["title"])
#         except:
#             restaurant_category_3.append(missing_api_result)
    
#         # not all results have all fields; to prevent error, try/except error handling, assigning "" (empty value)
# #         try:
# #             restaurant_category_test.append(yelp_results["categories"][0]["title"])
            
# #             # not all results have > 1 category; in order to create dict, all lists must be same size - must assign "" when there is only one category
# #             if len(yelp_results[0]["categories"]) >= 1:
# #                 restaurant_category_1.append(yelp_results["categories"][0]["title"])
# #             else:
# #                 restaurant_category_1.append(missing_api_result)
            
# #             if len(yelp_results[0]["categories"]) >= 2:
# #                 restaurant_category_2.append(yelp_results["categories"][1]["title"])
# #             else:
# #                 restaurant_category_2.append(missing_api_result)
            
# #             if len(yelp_results[0]["categories"]) >= 3:
# #                 restaurant_category_3.append(yelp_results["categories"][2]["title"])
# #             else:
# #                 restaurant_category_3.append(missing_api_result)
# #         except:
# #             restaurant_category_test.append(missing_api_result)
        
#         try:
#             restaurant_latitude.append(yelp_results["coordinates"]["latitude"])
#         except:
#             restaurant_latitude.append(missing_api_result)
            
#         try:
#             restaurant_longitude.append(yelp_results["coordinates"]["longitude"])
#         except:
#             restaurant_longitude.append(missing_api_result)
            
# #         try:
# #             restaurant_display_phone.append(yelp_results["display_phone"])
# #         except:
# #             restaurant_display_phone.append(missing_api_result)
            
# #         try:
# #             restaurant_distance.append(yelp_results["distance"])
# #         except:
# #             restaurant_distance.append(missing_api_result)
            
#         try:
#             restaurant_id.append(yelp_results["id"])
#         except:
#             restaurant_id.append(missing_api_result)
            
# #         try:
# #             restaurant_alias.append(yelp_results["alias"])
# #         except:
# #             restaurant_alias.append(missing_api_result)
            
# #         try:
# #             restaurant_image_url.append(yelp_results["image_url"])
# #         except:
# #             restaurant_image_url.append(missing_api_result)
            
#         try:
#             restaurant_is_closed.append(yelp_results["is_closed"])
#         except:
#             restaurant_is_closed.append(missing_api_result)
            
#         try:
#             restaurant_address1.append(yelp_results["location"]["address1"])
#         except:
#             restaurant_address1.append(missing_api_result)
            
#         try:
#             restaurant_address2.append(yelp_results["location"]["address2"])
#         except:
#             restaurant_address2.append(missing_api_result)
            
# #         try:
# #             restaurant_address3.append(yelp_results["location"]["address3"])
# #         except:
# #             restaurant_address3.append(missing_api_result)
            
#         try:
#             restaurant_city.append(yelp_results["location"]["city"])
#         except:
#             restaurant_city.append(missing_api_result)
            
# #         try:
# #             restaurant_country.append(yelp_results["location"]["country"])
# #         except:
# #             restaurant_country.append(missing_api_result)
            
# #         try:
# #             restaurant_display_address.append(yelp_results["location"]["display_address"])
# #         except:
# #             restaurant_display_address.append(missing_api_result)
            
#         try:
#             restaurant_state.append(yelp_results["location"]["state"])
#         except:
#             restaurant_state.append(missing_api_result)
            
#         try:
#             restaurant_zip_code.append(yelp_results["location"]["zip_code"])
#         except:
#             restaurant_zip_code.append(missing_api_result)
            
#         try:
#             restaurant_name.append(yelp_results["name"])
#         except:
#             restaurant_name.append(missing_api_result)
            
#         try:
#             restaurant_phone.append(yelp_results["phone"])
#         except:
#             restaurant_phone.append(missing_api_result)
            
#         try:
#             restaurant_price.append(yelp_results["price"])
#         except:
#             restaurant_price.append(missing_api_result)
            
#         try:
#             restaurant_rating.append(yelp_results["rating"])
#         except:
#             restaurant_rating.append(missing_api_result)
            
#         try:
#             restaurant_review_count.append(yelp_results["review_count"])
#         except:
#             restaurant_review_count.append(missing_api_result)
            
# #         try:
# #             restaurant_url.append(yelp_results["url"])
# #         except:
# #             restaurant_url.append(missing_api_result)
#     except:
#         pass
    
#     counter += 1

In [115]:
# setup other variable (initially as blank); to be updated, used in for loop with API call for each city
# create empty lists for the data
yelp_category_1 = []
yelp_category_2 = []
yelp_category_3 = []
yelp_latitude = []
yelp_longitude = []
yelp_display_phone = []
yelp_distance = []
yelp_id = []
yelp_alias = []
yelp_image_url = []
yelp_is_closed = []
yelp_address_1 = []
yelp_address_2 = []
yelp_address_3 = []
yelp_city = []
yelp_country = []
yelp_display_address = []
yelp_state = []
yelp_zip_code = []
yelp_name = []
yelp_phone = []
yelp_price = []
yelp_rating = []
yelp_review_count = []
yelp_url = []
yelp_transactions = []
yelp_region_center_lat = []
yelp_region_center_long = []

In [116]:
for index, row in df.iterrows():
    # get restaurant data from df, setting respective variables for that restaurant
    search_name = row["restaurant_name"]
    search_street_number = row["street_number"]
    search_street_name = row["street_name"]
    search_zip_code = row["zip_code"]
    search_lat = row["lat"]
    search_lng = row["long"]
    
    # set API request parameters
    params = {
#         "term": f"restaurant,{search_name}",
        "term": f"{search_name}",
        "location": f"{search_street_number} {search_street_name}, {search_zip_code}",
#         "location": "Dallas",
#         "latitude": xx,
#         "longitude": xx,
        "radius": 1000,
        "limit": 3,
        "sort_by": "best_match"
    }
    
    # set yelp_response to results from API request
    yelp_response = requests.get(url, params=params, headers=headers_1).json()
    
    # traverse json object, set yelp_results to only business data for the best match result (0 index position)
    try:
        yelp_results = yelp_response["businesses"][0]
#     yelp_results = yelp_response["businesses"][0]
#     yelp_results = yelp_response["businesses"]

        # not all results have all fields; to prevent error, try/except error handling, assigning "" (empty value)
        try:
            yelp_category_1 = yelp_results["categories"][0]["title"]
            df.loc[index, "yelp_category_1"] = yelp_category_1
        except:
            pass
#             df.loc[index, "yelp_restaurant_category_1"] = missing_api_result
            
        try:
            yelp_category_2 = yelp_results["categories"][1]["title"]
            df.loc[index, "yelp_category_2"] = yelp_category_2
        except:
            pass
            
        try:
            yelp_category_3 = yelp_results["categories"][2]["title"]
            df.loc[index, "yelp_category_3"] = yelp_category_3
        except:
            pass
        
        try:
            yelp_latitude = yelp_results["coordinates"]["latitude"]
            df.loc[index, "yelp_latitude"] = yelp_latitude
        except:
            pass
        
        try:
            yelp_longitude = yelp_results["coordinates"]["longitude"]
            df.loc[index, "yelp_longitude"] = yelp_longitude
        except:
            pass
        
#         try:
#             yelp_display_phone = yelp_results["display_phone"]
#             df.loc[index, "yelp_display_phone"] = yelp_display_phone
#         except:
#             pass
        
#         try:
#             yelp_distance = yelp_results["distance"]
#             df.loc[index, "yelp_distance"] = yelp_distance
#         except:
#             pass
        
        try:
            yelp_id = yelp_results["id"]
            df.loc[index, "yelp_id"] = yelp_id
        except:
            pass
        
#         try:
#             yelp_alias = yelp_results["alias"]
#             df.loc[index, "yelp_alias"] = yelp_alias
#         except:
#             pass
        
#         try:
#             yelp_image_url = yelp_results["image_url"]
#             df.loc[index, "yelp_image_url"] = yelp_image_url
#         except:
#             pass
        
        try:
            yelp_is_closed = yelp_results["is_closed"]
            df.loc[index, "yelp_is_closed"] = yelp_is_closed
        except:
            pass
        
        try:
            yelp_is_closed = yelp_results["is_closed"]
            df.loc[index, "yelp_is_closed"] = yelp_is_closed
        except:
            pass
        
        try:
            yelp_address_1 = yelp_results["location"]["address1"]
            df.loc[index, "yelp_address_1"] = yelp_address_1
        except:
            pass
        
        try:
            yelp_address_2 = yelp_results["location"]["address2"]
            df.loc[index, "yelp_address_2"] = yelp_address_2
        except:
            pass
        
#         try:
#             yelp_address_3 = yelp_results["location"]["address3"]
#             df.loc[index, "yelp_address_3"] = yelp_address_3
#         except:
#             pass
        
        try:
            yelp_city = yelp_results["location"]["city"]
            df.loc[index, "yelp_city"] = yelp_city
        except:
            pass
        
#         try:
#             yelp_country = yelp_results["location"]["country"]
#             df.loc[index, "yelp_country"] = yelp_country
#         except:
#             pass
        
#         try:
#             yelp_display_address = yelp_results["location"]["display_address"]
#             df.loc[index, "yelp_display_address"] = yelp_display_address
#         except:
#             pass
        
        try:
            yelp_state = yelp_results["location"]["state"]
            df.loc[index, "yelp_state"] = yelp_state
        except:
            pass
        
        try:
            yelp_zip_code = yelp_results["location"]["zip_code"]
            df.loc[index, "yelp_zip_code"] = yelp_zip_code
        except:
            pass
        
        try:
            yelp_name = yelp_results["name"]
            df.loc[index, "yelp_name"] = yelp_name
        except:
            pass
        
        try:
            yelp_phone = yelp_results["phone"]
            df.loc[index, "yelp_phone"] = yelp_phone
        except:
            pass
        
        try:
            yelp_price = yelp_results["price"]
            df.loc[index, "yelp_price"] = yelp_price
        except:
            pass
        
        try:
            yelp_rating = yelp_results["rating"]
            df.loc[index, "yelp_rating"] = yelp_rating
        except:
            pass
        
        try:
            yelp_review_count = yelp_results["review_count"]
            df.loc[index, "yelp_review_count"] = yelp_review_count
        except:
            pass
        
#         try:
#             yelp_url = yelp_results["url"]
#             df.loc[index, "yelp_url"] = yelp_url
#         except:
#             pass
        
    except:
        pass

/Users/shanergy/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:376: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = _infer_fill_value(value)
/Users/shanergy/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:494: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[item] = s

In [117]:
df

,restaurant_name,inspection_type,inspection_date,inspection_score,street_number,street_name,street_unit,zip_code,street_address,inspection_month,...,yelp_address_2,yelp_city,yelp_state,yelp_zip_code,yelp_name,yelp_phone,yelp_price,yelp_rating,yelp_review_count,yelp_category_3
0,2204,Routine,43644,95,2204,ELM,NaN,75201,3922 SIMPSON ST,43617,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,13209,Routine,43684,96,13209,C F HAWN,NaN,75253,1910 S HARWOOD ST,43678,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,44023,Routine,43817,80,1102,KIEST,NaN,75224,1201 ELM ST #LL09,43800,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,"""LET'S DO LUNCH""",Routine,43705,100,1720,REGAL,#105,75235,2704 ELM ST,43678,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1-STOP SHOP,Routine,43804,91,1512,BELTLINE,#2,75253,238 W ILLINOIS AVE,43800,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,12 CUTS STEAK HOUSE,Routine,43768,91,18010,DALLAS,NaN,75287,2821 GREENVILLE AVE,43739,...,NaN,Dallas,TX,75287,12 Cuts Brazilian Steakhouse,+14697797012,$$$,5.0,53.0,NaN
6,13910 SHELL,Routine,43801,96,13910,CENTRAL,NaN,75243,214 N AKARD ST,43800,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,15695 HEIGHTS PREP,Routine,43760,91,2806,CANADA,NaN,75212,6610 LAKE JUNE RD,43739,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,15710 FOODA-CHASE TOWER,Routine,43614,96,2200,ROSS,NaN,75201,3818 W ILLINOIS AVE,43586,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,15734 3D CANTINA,Routine,43769,82,2707,MLK,#130,75215,6057 SKILLMAN ST,43739,...,Ste 103,Dallas,TX,75215,3D Daiquiri Bar & Grill,+12144286800,$,5.0,13.0,American (New)
10,15742 TEXAS FOOD MART,Routine,43665,82,2984,WHEATLAND,#E,75037,7812 GREAT TRINITY FOREST WAY #300,43647,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,15757 JAZEN TEA,Routine,43472,96,11613,CENTRAL,#106A,75243,14010 COIT RD,43466,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,15789 THE MERCHANT AT LOWER GREENVILLE,Routine,43630,96,1924,GREENVILLE,NaN,75206,3206 W DAVIS ST #B,43617,...,,Dallas,TX,75206,Laurel Tavern,+14693990613,$$,4.0,94.0,Beer Bar
13,15805 DOTTEA,Routine,43816,93,14902,PRESTON,#500,75254,2324 W CLARENDON DR,43800,...,Ste 500,Dallas,TX,75254,Dottea,+14693727533,$,4.5,88.0,Juice Bars & Smoothies
14,1600 CAFE,Routine,43790,94,1600,VICEROY,#125,75235,2500 VICTORY AVE PLZA #1027,43770,...,None,Dallas,TX,75235,7-Eleven,+12146382195,$,4.0,5.0,Coffee & Tea
15,"16096 TRINITY BASIN PREPARATORY, INC",Routine,43746,100,2524,LEDBETTER,BU4,75237,5365 SPRING VALLEY RD #101,43739,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,16152 VIDORRA,Routine,43605,84,2642,MAIN,#100,75226,5956 SHERRY LN #1700,43586,...,None,Dallas,TX,75226,Vidorra,+19722150640,$$,3.0,463.0,Cocktail Bars
17,16159 CORELOGIC MICROMARKET,Routine,43531,100,3001,HACKBERRY,NaN,75063,7995 LBJ STE #118,43525,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,16161 AH BELO DALLAS MORNING NEWS MICROMARKET,Routine,43490,99,1954,COMMERCE,NaN,75201,325 N SAINT PAUL ST #P5,43466,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,16162 - KPMG,Routine,43640,95,2323,ROSS,NaN,75201,4302 BRYAN ST,43617,...,,Dallas,TX,75201,Hall Art's Garage,+12148559332,NaN,1.0,2.0,NaN
20,1717 RESTAURANT,Routine,43738,91,1717,HARWOOD,NaN,75201,2660 ROBERT B CULLUM BLVD,43709,...,None,Dallas,TX,75201,Serendipity Labs - Dallas,+12149743918,NaN,5.0,3.0,NaN
21,20 FEET,Routine,43706,97,1160,PEAVY,NaN,75218,1400 HI LINE DR #120,43678,...,,Dallas,TX,75218,20 Feet Seafood Joint,+19727077442,$$,4.0,526.0,NaN
22,2100 DELI,Routine,43644,80,2100,MCKINNEY,#150,75201,3520 GREENVILLE AVE,43617,...,Ste 150,Dallas,TX,75201,2100 Deli,+12149097296,$,3.5,3.0,NaN
23,2817 MAPLE LLC,Routine,43727,86,2817,MAPLE,#210,75201,6887 SHADY BROOK LN,43709,...,,Dallas,TX,75204,Carlisle on the Katy Trail,+12147421296,NaN,3.0,29.0,NaN
24,3 FORKS RESTAURANT,Routine,43703,88,17776,DALLAS,NaN,75287,2800 ROUTH ST #170,43678,...,,Dallas,TX,75287,III Forks,+19722671776,$$$,4.0,675.0,NaN
25,3015 AT TRINITY GROVES,Routine,43823,98,3015,GULDEN,#100,75212,8055 S LOOP 12,43800,...,,Dallas,TX,75212,3015 At Trinity Groves,+12149393015,NaN,4.0,16.0,NaN
26,303 BAR & GRILL,Routine,43826,97,303,DAVIS,NaN,75208,8112 S HAMPTON RD,43800,...,,Dallas,TX,75208,303 Grill,+12149423030,$$,3.5,262.0,Bars
27,303 BAR & GRILL (BAR AREA),Routine,43782,94,303,DAVIS,NaN,75208,8120 W CAMP WISDOM RD FLR 1,43770,...,,Dallas,TX,75208,Ten Bells Tavern,+12149432677,$$,4.0,289.0,NaN
28,3131 LOUNGE,Routine,43738,100,3131,MAIN,NaN,75219,8687 N CENTRAL EXPW,43709,...,,Dallas,TX,75226,Hide,+12143968050,$$,4.5,384.0,NaN
29,3ELEVEN KITCHEN & COCKTAILS,Routine,43776,88,311,MARKET,#100,75202,8390 N STEMMONS FRWY #B,43770,...,Ste 100,Dallas,TX,75202,3 Eleven Kitchen & Cocktails,+12147441423,$$,4.0,267.0,Breakfast & Brunch
30,4 SEASONS FOOD MART,Routine,43752,85,19090,MARSH,NaN,75287,3102 OAK LAWN AVE #110,43739,...,,Dallas,TX,75287,Conoco & 4 Seasons Food Mart,+19723073350,NaN,4.5,2.0,NaN
31,45 MINT,Routine,43698,97,14902,PRESTON,#512B,75254,2326 N HENDERSON AVE,43678,...,Ste 512B,Dallas,TX,75254,45 Mint Vietnamese Bistro,+19723874545,$,4.0,209.0,NaN
32,5 STAR CHEVRON,Routine,43517,90,3301,FORT WORTH,NaN,75211,9222 JOHN W. CARPENTER FRWY,43497,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,50286 SLAYTER'S 50/50 UPSTAIRS BAR (2ND FL),Routine,43511,100,2817,GREENVILLE,NaN,75206,6867 GREENVILLE AVE,43497,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,6-TWELVE FOOD STORE,Routine,43555,93,1221,HAMPTON,NaN,75208,1722 ROUTH ST STE #110,43525,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,6-TWELVE FOOD STORE #102,Routine,43776,80,1910,EDGEFIELD,NaN,75224,3105 W DAVIS ST,43770,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,7 - ELEVEN #35421,Routine,43753,93,10804,PRESTON,NaN,75230,116 W JEFFERSON BLVD,43739,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,7- ELEVEN CONVENIENCE STORE #21368C,Routine,43727,94,2120,GREENVILLE,NaN,75206,3636 FRANKFORD RD 390,43709,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,7-11 #18765,Routine,43777,83,111,CARROLL,NaN,75226,12107 ABRAMS RD,43770,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,7-11 #25080,Routine,43467,98,17605,MIDWAY,NaN,75252,2741 N STEMMONS FRWY,43466,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,7-11 #26151,Routine,43637,80,1410,ILLINOIS,NaN,75216,2222 FORT WORTH AVE #160,43617,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,7-11 #27529,Routine,43745,98,18101,COIT,NaN,75252,2838 W DAVIS ST,43739,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,7-11CONVENIENCE STORE #33441,Routine,43542,98,2608,ELM,NaN,75226,5601 SEARS ST,43525,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,7-ELEVEN,Routine,43808,89,3230,DAVIS,NaN,75211,909 N WASHINGTON AVE,43800,...,,Dallas,TX,75208,7-Eleven,+12149441499,$,3.5,8.0,Coffee & Tea
44,7-ELEVEN #12200,Routine,43746,93,2529,OAK LAWN,NaN,75219,5410 LBJ FRWY,43739,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,7-ELEVEN #18717,Routine,43759,80,2223,BECKLEY,NaN,75224,4023 LEMMON AVE,43739,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,7-ELEVEN #20769,Routine,43508,86,10340,FOREST,#106,75243,10788 HARRY HINES BLVD E28,43497,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,7-ELEVEN #26771C,Routine,43488,91,18118,MIDWAY,NaN,75252,2911 LOMBARDY LN #101,43466,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,7-ELEVEN #27206,Routine,43522,91,13601,C F HAWN,NaN,75253,2115 BUTLER ST,43497,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,7-ELEVEN #34102,Routine,43475,84,2061,FORT WORTH,NaN,75208,3500 GOLDMAN ST,43466,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# for row in df["restaurant_name"]:
    
#     # get restaurant data from df, setting respective variables for that restaurant
#     search_name = df["restaurant_name"][counter]
#     search_street_number = df["street_number"][counter]
#     search_street_name = df["street_name"][counter]
#     search_zip_code = df["zip_code"][counter]
# #     search_lat = df["lat"][counter]
# #     search_lng = df["long"][counter]
    
#     # set API request parameters
#     params = {
# #         "term": f"restaurant,{search_name}",
#         "term": f"{search_name}",
#         "location": f"{search_street_number} {search_street_name}, {search_zip_code}",
# #         "location": "Dallas",
# #         "latitude": xx,
# #         "longitude": xx,
#         "radius": 1000,
#         "limit": 3,
#         "sort_by": "best_match"
#     }
    
#     # set yelp_response to results from API request
#     yelp_response = requests.get(url, params=params, headers=headers_1).json()
    
#     # traverse json object, set yelp_results to only business data for the best match result (0 index position)
#     try:
#         yelp_results = yelp_response["businesses"][0]
# #     yelp_results = yelp_response["businesses"][0]
# #     yelp_results = yelp_response["businesses"]

#         try:
#             restaurant_category_1.append(yelp_results["categories"][0]["title"])
#         except:
#             restaurant_category_1.append(missing_api_result)
            
#         try:
#             restaurant_category_2.append(yelp_results["categories"][1]["title"])
#         except:
#             restaurant_category_2.append(missing_api_result)
            
#         try:
#             restaurant_category_3.append(yelp_results["categories"][2]["title"])
#         except:
#             restaurant_category_3.append(missing_api_result)
    
#         # not all results have all fields; to prevent error, try/except error handling, assigning "" (empty value)
# #         try:
# #             restaurant_category_test.append(yelp_results["categories"][0]["title"])
            
# #             # not all results have > 1 category; in order to create dict, all lists must be same size - must assign "" when there is only one category
# #             if len(yelp_results[0]["categories"]) >= 1:
# #                 restaurant_category_1.append(yelp_results["categories"][0]["title"])
# #             else:
# #                 restaurant_category_1.append(missing_api_result)
            
# #             if len(yelp_results[0]["categories"]) >= 2:
# #                 restaurant_category_2.append(yelp_results["categories"][1]["title"])
# #             else:
# #                 restaurant_category_2.append(missing_api_result)
            
# #             if len(yelp_results[0]["categories"]) >= 3:
# #                 restaurant_category_3.append(yelp_results["categories"][2]["title"])
# #             else:
# #                 restaurant_category_3.append(missing_api_result)
# #         except:
# #             restaurant_category_test.append(missing_api_result)
        
#         try:
#             restaurant_latitude.append(yelp_results["coordinates"]["latitude"])
#         except:
#             restaurant_latitude.append(missing_api_result)
            
#         try:
#             restaurant_longitude.append(yelp_results["coordinates"]["longitude"])
#         except:
#             restaurant_longitude.append(missing_api_result)
            
# #         try:
# #             restaurant_display_phone.append(yelp_results["display_phone"])
# #         except:
# #             restaurant_display_phone.append(missing_api_result)
            
# #         try:
# #             restaurant_distance.append(yelp_results["distance"])
# #         except:
# #             restaurant_distance.append(missing_api_result)
            
#         try:
#             restaurant_id.append(yelp_results["id"])
#         except:
#             restaurant_id.append(missing_api_result)
            
# #         try:
# #             restaurant_alias.append(yelp_results["alias"])
# #         except:
# #             restaurant_alias.append(missing_api_result)
            
# #         try:
# #             restaurant_image_url.append(yelp_results["image_url"])
# #         except:
# #             restaurant_image_url.append(missing_api_result)
            
#         try:
#             restaurant_is_closed.append(yelp_results["is_closed"])
#         except:
#             restaurant_is_closed.append(missing_api_result)
            
#         try:
#             restaurant_address1.append(yelp_results["location"]["address1"])
#         except:
#             restaurant_address1.append(missing_api_result)
            
#         try:
#             restaurant_address2.append(yelp_results["location"]["address2"])
#         except:
#             restaurant_address2.append(missing_api_result)
            
# #         try:
# #             restaurant_address3.append(yelp_results["location"]["address3"])
# #         except:
# #             restaurant_address3.append(missing_api_result)
            
#         try:
#             restaurant_city.append(yelp_results["location"]["city"])
#         except:
#             restaurant_city.append(missing_api_result)
            
# #         try:
# #             restaurant_country.append(yelp_results["location"]["country"])
# #         except:
# #             restaurant_country.append(missing_api_result)
            
# #         try:
# #             restaurant_display_address.append(yelp_results["location"]["display_address"])
# #         except:
# #             restaurant_display_address.append(missing_api_result)
            
#         try:
#             restaurant_state.append(yelp_results["location"]["state"])
#         except:
#             restaurant_state.append(missing_api_result)
            
#         try:
#             restaurant_zip_code.append(yelp_results["location"]["zip_code"])
#         except:
#             restaurant_zip_code.append(missing_api_result)
            
#         try:
#             restaurant_name.append(yelp_results["name"])
#         except:
#             restaurant_name.append(missing_api_result)
            
#         try:
#             restaurant_phone.append(yelp_results["phone"])
#         except:
#             restaurant_phone.append(missing_api_result)
            
#         try:
#             restaurant_price.append(yelp_results["price"])
#         except:
#             restaurant_price.append(missing_api_result)
            
#         try:
#             restaurant_rating.append(yelp_results["rating"])
#         except:
#             restaurant_rating.append(missing_api_result)
            
#         try:
#             restaurant_review_count.append(yelp_results["review_count"])
#         except:
#             restaurant_review_count.append(missing_api_result)
            
# #         try:
# #             restaurant_url.append(yelp_results["url"])
# #         except:
# #             restaurant_url.append(missing_api_result)
#     except:
#         pass
    
#     counter += 1

In [45]:
# # trying iterrows - need to add columns to existing dataframe to pass new data into


# counter = 0

# # yelp_response = []

# # for restaurant in dallas_open_data_df_limited:
# for row in dallas_open_data_df_limited["restaurant_name"]:
# # for index, row in dallas_open_data_df_limited.iterrows():
    
#     # get restaurant data from df and set as variable to pass through to API call
#     # restaurant search variables
#     search_name = dallas_open_data_df_limited["restaurant_name"][counter]
# #     search_address = dallas_open_data_df_limited["street_address"][counter]
#     search_street_number = dallas_open_data_df_limited["street_number"][counter]
#     search_street_name = dallas_open_data_df_limited["street_name"][counter]
#     search_zip_code = dallas_open_data_df_limited["zip_code"][counter]
#     search_lat = dallas_open_data_df_limited["lat"][counter]
#     search_lng = dallas_open_data_df_limited["long"][counter]
    
#     # set parameters
#     params = {"term": f"restaurant,{search_name}",
#               "location": f"{search_street_number} {search_street_name}, {search_zip_code}",
# #               "latitude": xx,
# #               "longitude": xx,
#               "radius": 100,
#               "limit": 5
#              }
    
#     yelp_response = requests.get(url, params=params, headers=headers_1).json()
# #     yelp_results = yelp_response["businesses"][0]
#     yelp_results = yelp_response["businesses"]
    
#     try:
#         restaurant_category_test.append(yelp_results[0]["categories"][0]["title"])
#     # not all results have > 1 category; in order to create dict, all lists must be same size - must assign "" when there is only one category
#         if len(yelp_results[0]["categories"]) >= 1:
#             restaurant_category_1.append(yelp_results[0]["categories"][0]["title"])
#         else:
#             restaurant_category_1.append(missing_api_result)
#         if len(yelp_results[0]["categories"]) >= 2:
#             restaurant_category_2.append(yelp_results[0]["categories"][1]["title"])
#         else:
#             restaurant_category_2.append(missing_api_result)
#         if len(yelp_results[0]["categories"]) >= 3:
#             restaurant_category_3.append(yelp_results[0]["categories"][2]["title"])
#         else:
#             restaurant_category_3.append(missing_api_result)
#     except:
#         restaurant_category_test.append(missing_api_result)
        
#     try:
#         restaurant_latitude.append(yelp_results[0]["coordinates"]["latitude"])
#     except:
#         restaurant_latitude.append(missing_api_result)
        
#     try:
#         restaurant_longitude.append(yelp_results[0]["coordinates"]["longitude"])
#     except:
#         restaurant_longitude.append(missing_api_result)
        
#     try:
#         restaurant_display_phone.append(yelp_results[0]["display_phone"])
#     except:
#         restaurant_display_phone.append(missing_api_result)
        
#     try:
#         restaurant_distance.append(yelp_results[0]["distance"])
#     except:
#         restaurant_distance.append(missing_api_result)
        
#     try:
#         restaurant_id.append(yelp_results[0]["id"])
#     except:
#         restaurant_id.append(missing_api_result)
        
#     try:
#         restaurant_alias.append(yelp_results[0]["alias"])
#     except:
#         restaurant_alias.append(missing_api_result)
        
#     try:
#         restaurant_image_url.append(yelp_results[0]["image_url"])
#     except:
#         restaurant_image_url.append(missing_api_result)
        
#     try:
#         restaurant_is_closed.append(yelp_results[0]["is_closed"])
#     except:
#         restaurant_is_closed.append(missing_api_result)
        
#     try:
#         restaurant_address1.append(yelp_results[0]["location"]["address1"])
#     except:
#         restaurant_address1.append(missing_api_result)
        
#     try:
#         restaurant_address2.append(yelp_results[0]["location"]["address2"])
#     except:
#         restaurant_address2.append(missing_api_result)
        
#     try:
#         restaurant_address3.append(yelp_results[0]["location"]["address3"])
#     except:
#         restaurant_address3.append(missing_api_result)
        
#     try:
#         restaurant_city.append(yelp_results[0]["location"]["city"])
#     except:
#         restaurant_city.append(missing_api_result)
        
#     try:
#         restaurant_country.append(yelp_results[0]["location"]["country"])
#     except:
#         restaurant_country.append(missing_api_result)
        
#     try:
#         restaurant_display_address.append(yelp_results[0]["location"]["display_address"])
#     except:
#         restaurant_display_address.append(missing_api_result)
        
#     try:
#         restaurant_state.append(yelp_results[0]["location"]["state"])
#     except:
#         restaurant_state.append(missing_api_result)
        
#     try:
#         restaurant_zip_code.append(yelp_results[0]["location"]["zip_code"])
#     except:
#         restaurant_zip_code.append(missing_api_result)
        
#     try:
#         restaurant_name.append(yelp_results[0]["name"])
#     except:
#         restaurant_name.append(missing_api_result)
        
#     try:
#         restaurant_phone.append(yelp_results[0]["phone"])
#     except:
#         restaurant_phone.append(missing_api_result)
        
# #     restaurant_price.append(yelp_results[0]["price"])
#     # not all results have Price; to prevent error, try/except error handling, assigning "", all lists must be same size - must assign "" when there is no Price
#     try:
#         restaurant_price.append(yelp_results[0]["price"])
#     except:
#         restaurant_price.append(missing_api_result)
#     try:
#         restaurant_rating.append(yelp_results[0]["rating"])
#     except:
#         restaurant_rating.append(missing_api_result)
#     try:
#         restaurant_review_count.append(yelp_results[0]["review_count"])
#     except:
#         restaurant_review_count.append(missing_api_result)
#     try:
#         restaurant_url.append(yelp_results[0]["url"])
#     except:
#         restaurant_url.append(missing_api_result)
    
#     counter += 1

In [97]:
yelp_response

{'businesses': [],
 'total': 0,
 'region': {'center': {'longitude': -96.85615539550781,
   'latitude': 32.76272732202159}}}

In [98]:
restaurant_name

['12 Cuts Brazilian Steakhouse',
 '3D Daiquiri Bar & Grill',
 'Laurel Tavern',
 'Dottea',
 '7-Eleven',
 'Vidorra',
 "Hall Art's Garage",
 'Serendipity Labs - Dallas',
 '20 Feet Seafood Joint',
 '2100 Deli',
 'Carlisle on the Katy Trail',
 'III Forks',
 '3015 At Trinity Groves',
 '303 Grill',
 'Ten Bells Tavern',
 'Hide',
 '3 Eleven Kitchen & Cocktails',
 'Conoco & 4 Seasons Food Mart',
 '45 Mint Vietnamese Bistro',
 '7-Eleven']

#### create dictionary using the lists populated from yelp_results json object

In [99]:
# create dictionary using the lists created from yelp_results json object
restaurant_dict = {"Name": restaurant_name,
#                    "Alias": restaurant_alias,
                   "Category1": restaurant_category_1,
                   "Category2": restaurant_category_2,
                   "Category3": restaurant_category_3,
                   "Rating": restaurant_rating,
                   "ReviewCount": restaurant_review_count,
                   "Price": restaurant_price,
                   "Lat": restaurant_latitude,
                   "Lng": restaurant_longitude,
                   "Address": restaurant_address1,
                   "Address2": restaurant_address2,
#                    "Address3": restaurant_address3,
                   "City": restaurant_city,
                   "State": restaurant_state,
#                    "Country": restaurant_country,
                   "Zip": restaurant_zip_code,
#                    "DisplayAddress": restaurant_display_address,
                   "Phone": restaurant_phone,
#                    "DisplayPhone": restaurant_display_phone,
#                    "ImageURL": restaurant_image_url,
#                    "URL": restaurant_url
#                    "Transactions": restaurant_transactions,
                   "Closed?": restaurant_is_closed,
#                    "ID": restaurant_id,
                  }

#### visualize restaurant_dict

In [100]:
restaurant_dict

{'Name': ['12 Cuts Brazilian Steakhouse',
  '3D Daiquiri Bar & Grill',
  'Laurel Tavern',
  'Dottea',
  '7-Eleven',
  'Vidorra',
  "Hall Art's Garage",
  'Serendipity Labs - Dallas',
  '20 Feet Seafood Joint',
  '2100 Deli',
  'Carlisle on the Katy Trail',
  'III Forks',
  '3015 At Trinity Groves',
  '303 Grill',
  'Ten Bells Tavern',
  'Hide',
  '3 Eleven Kitchen & Cocktails',
  'Conoco & 4 Seasons Food Mart',
  '45 Mint Vietnamese Bistro',
  '7-Eleven'],
 'Category1': ['Brazilian',
  'Mexican',
  'Cocktail Bars',
  'Bubble Tea',
  'Convenience Stores',
  'New Mexican Cuisine',
  'Parking',
  'Shared Office Spaces',
  'Seafood',
  'Delis',
  'Apartments',
  'Steakhouses',
  'Venues & Event Spaces',
  'Breakfast & Brunch',
  'Pubs',
  'Cocktail Bars',
  'Cocktail Bars',
  'Gas Stations',
  'Vietnamese',
  'Gas Stations'],
 'Category2': ['Steakhouses',
  'Burgers',
  'Gastropubs',
  'Coffee & Tea',
  'Gas Stations',
  'Mexican',
  '',
  'Venues & Event Spaces',
  '',
  '',
  '',
  'Seafood',
  'Caterers',
  'Burgers',
  'British',
  'American (New)',
  'American (Traditional)',
  'Grocery',
  '',
  'Convenience Stores'],
 'Category3': ['',
  'American (New)',
  'Beer Bar',
  'Juice Bars & Smoothies',
  'Coffee & Tea',
  'Cocktail Bars',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  'Bars',
  '',
  '',
  'Breakfast & Brunch',
  '',
  '',
  'Coffee & Tea'],
 'Rating': [5.0,
  5.0,
  4.0,
  4.5,
  4.0,
  3.0,
  1.0,
  5.0,
  4.0,
  3.5,
  3.0,
  4.0,
  4.0,
  3.5,
  4.0,
  4.5,
  4.0,
  4.5,
  4.0,
  3.5],
 'ReviewCount': [53,
  13,
  94,
  88,
  5,
  463,
  2,
  3,
  526,
  3,
  29,
  675,
  16,
  262,
  289,
  384,
  267,
  2,
  209,
  8],
 'Price': ['$$$',
  '$',
  '$$',
  '$',
  '$',
  '$$',
  '',
  '',
  '$$',
  '$',
  '',
  '$$$',
  '',
  '$$',
  '$$',
  '$$',
  '$$',
  '',
  '$',
  '$'],
 'Lat': [32.995445,
  32.7684989,
  32.81361,
  32.9512032540643,
  32.8364627892748,
  32.78341,
  32.7894402,
  32.78895,
  32.8395195007324,
  32.79166,
  32.8057807,
  32.99166,
  32.77883,
  32.74959,
  32.748695,
  32.784559,
  32.7812264,
  33.0114254632731,
  32.951184469241,
  32.7480843],
 'Lng': [-96.828465,
  -96.7696616,
  -96.76991,
  -96.8025894920654,
  -96.8636414408684,
  -96.78483,
  -96.7971725,
  -96.79706,
  -96.6967086791992,
  -96.80244,
  -96.8009541,
  -96.82832,
  -96.8277407,
  -96.82697,
  -96.825974,
  -96.782935,
  -96.8070088,
  -96.8569151019361,
  -96.803003,
  -96.8563447],
 'Address': ['18010 Dallas Pkwy',
  '2707 Martin Luther King Jr Blvd',
  '1920 Greenville Ave',
  '14902 Preston Rd',
  '8402 Harry Hines Blvd',
  '2642 Main St',
  '2301 Ross Ave',
  '2323 Ross Ave',
  '1160 Peavy Rd',
  '2100 McKinney Ave',
  '3140 N Hall St',
  '17776 Dallas Pkwy',
  '3015 Gulden Ln',
  '303 W Davis St',
  '232 W 7th St',
  '2816 Elm St',
  '311 N Market St',
  '19090 Marsh Ln',
  '14902 Preston Rd',
  '408 N Hampton Rd'],
 'Address2': [None,
  'Ste 103',
  '',
  'Ste 500',
  None,
  None,
  '',
  None,
  '',
  'Ste 150',
  '',
  '',
  '',
  '',
  '',
  '',
  'Ste 100',
  '',
  'Ste 512B',
  ''],
 'City': ['Dallas',
  'Dallas',
  'Dallas',
  'Dallas',
  'Dallas',
  'Dallas',
  'Dallas',
  'Dallas',
  'Dallas',
  'Dallas',
  'Dallas',
  'Dallas',
  'Dallas',
  'Dallas',
  'Dallas',
  'Dallas',
  'Dallas',
  'Dallas',
  'Dallas',
  'Dallas'],
 'State': ['TX',
  'TX',
  'TX',
  'TX',
  'TX',
  'TX',
  'TX',
  'TX',
  'TX',
  'TX',
  'TX',
  'TX',
  'TX',
  'TX',
  'TX',
  'TX',
  'TX',
  'TX',
  'TX',
  'TX'],
 'Zip': ['75287',
  '75215',
  '75206',
  '75254',
  '75235',
  '75226',
  '75201',
  '75201',
  '75218',
  '75201',
  '75204',
  '75287',
  '75212',
  '75208',
  '75208',
  '75226',
  '75202',
  '75287',
  '75254',
  '75208'],
 'Phone': ['+14697797012',
  '+12144286800',
  '+14693990613',
  '+14693727533',
  '+12146382195',
  '+19722150640',
  '+12148559332',
  '+12149743918',
  '+19727077442',
  '+12149097296',
  '+12147421296',
  '+19722671776',
  '+12149393015',
  '+12149423030',
  '+12149432677',
  '+12143968050',
  '+12147441423',
  '+19723073350',
  '+19723874545',
  '+12149441499'],
 'Closed?': [False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  True,
  False]}

#### create data frame from dictionary

In [101]:
yelp_results

{'id': 'f3YG_0wsJaiDd4H-IgxirA',
 'alias': '7-eleven-dallas-72',
 'name': '7-Eleven',
 'image_url': 'https://s3-media4.fl.yelpcdn.com/bphoto/qr4JJ4u3ZsIPofp--bfvCA/o.jpg',
 'is_closed': False,
 'url': 'https://www.yelp.com/biz/7-eleven-dallas-72?adjust_creative=cqa3oghUiHI64DZLK-vRFw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=cqa3oghUiHI64DZLK-vRFw',
 'review_count': 8,
 'categories': [{'alias': 'servicestations', 'title': 'Gas Stations'},
  {'alias': 'convenience', 'title': 'Convenience Stores'},
  {'alias': 'coffee', 'title': 'Coffee & Tea'}],
 'rating': 3.5,
 'coordinates': {'latitude': 32.7480843, 'longitude': -96.8563447},
 'transactions': [],
 'price': '$',
 'location': {'address1': '408 N Hampton Rd',
  'address2': '',
  'address3': '',
  'city': 'Dallas',
  'zip_code': '75208',
  'country': 'US',
  'state': 'TX',
  'display_address': ['408 N Hampton Rd', 'Dallas, TX 75208']},
 'phone': '+12149441499',
 'display_phone': '(214) 944-1499',
 'distance': 1624.1781280627426}

In [102]:
restaurant_category_2

['Steakhouses',
 'Burgers',
 'Gastropubs',
 'Coffee & Tea',
 'Gas Stations',
 'Mexican',
 '',
 'Venues & Event Spaces',
 '',
 '',
 '',
 'Seafood',
 'Caterers',
 'Burgers',
 'British',
 'American (New)',
 'American (Traditional)',
 'Grocery',
 '',
 'Convenience Stores']

In [103]:
restaurant_df = pd.DataFrame(restaurant_dict)

#### visualize restaurant_df

In [104]:
# restaurant_df.dropna()
restaurant_df.head()

,Name,Category1,Category2,Category3,Rating,ReviewCount,Price,Lat,Lng,Address,Address2,City,State,Zip,Phone,Closed?
0,12 Cuts Brazilian Steakhouse,Brazilian,Steakhouses,,5.0,53,$$$,32.995445,-96.828465,18010 Dallas Pkwy,None,Dallas,TX,75287,+14697797012,False
1,3D Daiquiri Bar & Grill,Mexican,Burgers,American (New),5.0,13,$,32.768499,-96.769662,2707 Martin Luther King Jr Blvd,Ste 103,Dallas,TX,75215,+12144286800,False
2,Laurel Tavern,Cocktail Bars,Gastropubs,Beer Bar,4.0,94,$$,32.813610,-96.769910,1920 Greenville Ave,,Dallas,TX,75206,+14693990613,False
3,Dottea,Bubble Tea,Coffee & Tea,Juice Bars & Smoothies,4.5,88,$,32.951203,-96.802589,14902 Preston Rd,Ste 500,Dallas,TX,75254,+14693727533,False
4,7-Eleven,Convenience Stores,Gas Stations,Coffee & Tea,4.0,5,$,32.836463,-96.863641,8402 Harry Hines Blvd,None,Dallas,TX,75235,+12146382195,False

#### export restaurant_df to output CSV data file

In [118]:
# restaurant_df.to_csv(f"{output_data_filepath}yelp_test1.csv", encoding="utf-8", index=False)
# restaurant_df.to_csv(f"{output_data_filepath}yelp_test1.csv", encoding="UTF-16LE", index=False)

df.to_csv(f"{output_data_filepath}yelp_test1.csv", encoding="UTF-16LE", index=False)