In [1]:
# import dependencies
import pandas as pd
# import numpy as np
import requests
# import json
# from http import HTTPStatus

# bring in and use citipy to determine city based on latitude and longitude
# from citipy import citipy

# import api keys
from config import yelp_api_key_Austin, yelp_api_key_Shane, yelp_client_id_Shane

In [2]:
# csv data file filepath
# dallas_open_data = "../Other/Resources/dal_open_data_2019_inspection_month.csv"
# dallas_open_data = "../Other/Resources/test1.csv"
dallas_open_data = "../Other/Resources/full_test_1.csv"

In [3]:
# import Dallas Open Data CSV; with Google Lat/Lng
dallas_open_data_df = pd.read_csv(dallas_open_data, dtype="object", encoding="utf-8")

# visualize / show the top 5 rows of the data frame
# dallas_open_data_df.head()
dallas_open_data_df

,restaurant_name,inspection_type,inspection_date,inspection_score,street_number,street_name,street_unit,zip_code,street_address,inspection_month,inspection_year,lat,long,Unique Join
0,2204,Routine,43644,95,2204,ELM,NaN,75201,3922 SIMPSON ST,43617,FY2019,39.811585,-94.834959,NaN
1,13209,Routine,43684,96,13209,C F HAWN,NaN,75253,1910 S HARWOOD ST,43678,FY2019,32.6775,-96.604348,NaN
2,44023,Routine,43817,80,1102,KIEST,NaN,75224,1201 ELM ST #LL09,43800,FY2020,32.705756,-96.840532,NaN
3,"""LET'S DO LUNCH""",Routine,43705,100,1720,REGAL,#105,75235,2704 ELM ST,43678,FY2019,32.836816,-96.872095,NaN
4,1-STOP SHOP,Routine,43804,91,1512,BELTLINE,#2,75253,238 W ILLINOIS AVE,43800,FY2020,32.681431,-96.595947,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3180,ZIPPERS,Routine,43551,93,3333,FITZHUGH,NaN,75204,9496 WEBB CHAPEL RD,43525,FY2019,32.817108,-96.794074,NaN
3181,ZIZIKI'S,Routine,43726,85,11661,PRESTON,#309,75230,1411 N ZANG BLVD,43709,FY2019,42.080266,-90.016109,NaN
3182,ZODIAC RESTAURANT BAR,Routine,43748,100,1626,MAIN,NaN,75201,2534 ROYAL LN #A-14,43739,FY2020,37.375563,-120.723492,NaN
3183,ZOE'S KITCHEN #0031,Routine,43775,88,2009,ABRAMS,NaN,75214,3312 N BUCKNER BLVD,43770,FY2020,28.835643,-81.654156,NaN
3184,ZRG CONCEPTS,Routine,43724,96,2505,FITZHUGH,NaN,75204,527 SUNSET AVE,43709,FY2019,32.812409,-96.783502,NaN

In [28]:
dallas_open_data_df_limited = dallas_open_data_df.head()
dallas_open_data_df_limited

# restaurant search variables
search_name = ""
search_address = ""
search_street_number = ""
search_street_name = ""
search_zip_code = ""
search_lat = ""
search_lng = ""

In [29]:
dallas_open_data_df_limited

,restaurant_name,inspection_type,inspection_date,inspection_score,street_number,street_name,street_unit,zip_code,street_address,inspection_month,inspection_year,lat,long,Unique Join
0,2204,Routine,43644,95,2204,ELM,NaN,75201,3922 SIMPSON ST,43617,FY2019,39.811585,-94.834959,NaN
1,13209,Routine,43684,96,13209,C F HAWN,NaN,75253,1910 S HARWOOD ST,43678,FY2019,32.6775,-96.604348,NaN
2,44023,Routine,43817,80,1102,KIEST,NaN,75224,1201 ELM ST #LL09,43800,FY2020,32.705756,-96.840532,NaN
3,"""LET'S DO LUNCH""",Routine,43705,100,1720,REGAL,#105,75235,2704 ELM ST,43678,FY2019,32.836816,-96.872095,NaN
4,1-STOP SHOP,Routine,43804,91,1512,BELTLINE,#2,75253,238 W ILLINOIS AVE,43800,FY2020,32.681431,-96.595947,NaN

In [30]:
# # Dallas, TX, US Lat/Long: 32.7767Â° N, 96.7970Â° W
# dallas_lat = 32.7767
# dallas_lng = -96.7970

# # testcity = citipy.nearest_city(dallas_lat,dallas_lng).city_name
# testcity = citipy.nearest_city(dallas_lat,dallas_lng).city_name
# print(testcity)

In [31]:
# set the output csv file & png image output data filepath
output_data_filepath = "output_data/"

# set API key variables to pass through get request
api_key_1 = yelp_api_key_Shane
api_key_2 = yelp_api_key_Austin
# headers = {'Authorization': 'Bearer %s' % api_key}
headers_1 = {'Authorization': 'Bearer %s' % api_key_1}
headers_2 = {'Authorization': 'Bearer %s' % api_key_2}

# set url
url = 'https://api.yelp.com/v3/businesses/search'
#     'https://api.yelp.com/v3/businesses/{id}''

In [44]:
# create empty lists for the data
# restaurant_categories = []
restaurant_category_test = []
restaurant_category_1 = []
restaurant_category_2 = []
restaurant_category_3 = []
restaurant_latitude = []
restaurant_longitude = []
restaurant_display_phone = []
restaurant_distance = []
restaurant_id = []
restaurant_alias = []
restaurant_image_url = []
restaurant_is_closed = []
restaurant_address1 = []
restaurant_address2 = []
restaurant_address3 = []
restaurant_city = []
restaurant_country = []
restaurant_display_address = []
restaurant_state = []
restaurant_zip_code = []
restaurant_name = []
restaurant_phone = []
restaurant_price = []
restaurant_rating = []
restaurant_review_count = []
restaurant_url = []
restaurant_transactions = []
restaurant_region_center_lat = []
restaurant_region_center_long = []

missing_api_result = ""

In [33]:
counter = 0

# yelp_response = []

# for restaurant in dallas_open_data_df_limited:
for row in dallas_open_data_df_limited["restaurant_name"]:
    
    # get restaurant data from df and set as variable to pass through to API call
    # restaurant search variables
    search_name = dallas_open_data_df_limited["restaurant_name"][counter]
#     search_address = dallas_open_data_df_limited["street_address"][counter]
    search_street_number = dallas_open_data_df_limited["street_number"][counter]
    search_street_name = dallas_open_data_df_limited["street_name"][counter]
    search_zip_code = dallas_open_data_df_limited["zip_code"][counter]
    search_lat = dallas_open_data_df_limited["lat"][counter]
    search_lng = dallas_open_data_df_limited["long"][counter]
    
    # set parameters
    params = {"term": f"restaurant,{search_name}",
              "location": f"{search_street_number} {search_street_name}, {search_zip_code}",
#               "latitude": xx,
#               "longitude": xx,
              "radius": 100,
              "limit": 5
             }
    
    yelp_response = requests.get(url, params=params, headers=headers_1).json()
#     yelp_results = yelp_response["businesses"][0]
    yelp_results = yelp_response["businesses"]
    
    try:
        restaurant_category_test.append(yelp_results[0]["categories"][0]["title"])
    # not all results have > 1 category; in order to create dict, all lists must be same size - must assign "" when there is only one category
        if len(yelp_results[0]["categories"]) >= 1:
            restaurant_category_1.append(yelp_results[0]["categories"][0]["title"])
        else:
            restaurant_category_1.append(missing_api_result)
        if len(yelp_results[0]["categories"]) >= 2:
            restaurant_category_2.append(yelp_results[0]["categories"][1]["title"])
        else:
            restaurant_category_2.append(missing_api_result)
        if len(yelp_results[0]["categories"]) >= 3:
            restaurant_category_3.append(yelp_results[0]["categories"][2]["title"])
        else:
            restaurant_category_3.append(missing_api_result)
    except:
        restaurant_category_test.append(missing_api_result)
        
    try:
        restaurant_latitude.append(yelp_results[0]["coordinates"]["latitude"])
    except:
        restaurant_latitude.append(missing_api_result)
        
    try:
        restaurant_longitude.append(yelp_results[0]["coordinates"]["longitude"])
    except:
        restaurant_longitude.append(missing_api_result)
        
    try:
        restaurant_display_phone.append(yelp_results[0]["display_phone"])
    except:
        restaurant_display_phone.append(missing_api_result)
        
    try:
        restaurant_distance.append(yelp_results[0]["distance"])
    except:
        restaurant_distance.append(missing_api_result)
        
    try:
        restaurant_id.append(yelp_results[0]["id"])
    except:
        restaurant_id.append(missing_api_result)
        
    try:
        restaurant_alias.append(yelp_results[0]["alias"])
    except:
        restaurant_alias.append(missing_api_result)
        
    try:
        restaurant_image_url.append(yelp_results[0]["image_url"])
    except:
        restaurant_image_url.append(missing_api_result)
        
    try:
        restaurant_is_closed.append(yelp_results[0]["is_closed"])
    except:
        restaurant_is_closed.append(missing_api_result)
        
    try:
        restaurant_address1.append(yelp_results[0]["location"]["address1"])
    except:
        restaurant_address1.append(missing_api_result)
        
    try:
        restaurant_address2.append(yelp_results[0]["location"]["address2"])
    except:
        restaurant_address2.append(missing_api_result)
        
    try:
        restaurant_address3.append(yelp_results[0]["location"]["address3"])
    except:
        restaurant_address3.append(missing_api_result)
        
    try:
        restaurant_city.append(yelp_results[0]["location"]["city"])
    except:
        restaurant_city.append(missing_api_result)
        
    try:
        restaurant_country.append(yelp_results[0]["location"]["country"])
    except:
        restaurant_country.append(missing_api_result)
        
    try:
        restaurant_display_address.append(yelp_results[0]["location"]["display_address"])
    except:
        restaurant_display_address.append(missing_api_result)
        
    try:
        restaurant_state.append(yelp_results[0]["location"]["state"])
    except:
        restaurant_state.append(missing_api_result)
        
    try:
        restaurant_zip_code.append(yelp_results[0]["location"]["zip_code"])
    except:
        restaurant_zip_code.append(missing_api_result)
        
    try:
        restaurant_name.append(yelp_results[0]["name"])
    except:
        restaurant_name.append(missing_api_result)
        
    try:
        restaurant_phone.append(yelp_results[0]["phone"])
    except:
        restaurant_phone.append(missing_api_result)
        
#     restaurant_price.append(yelp_results[0]["price"])
    # not all results have Price; to prevent error, try/except error handling, assigning "", all lists must be same size - must assign "" when there is no Price
    try:
        restaurant_price.append(yelp_results[0]["price"])
    except:
        restaurant_price.append(missing_api_result)
    try:
        restaurant_rating.append(yelp_results[0]["rating"])
    except:
        restaurant_rating.append(missing_api_result)
    try:
        restaurant_review_count.append(yelp_results[0]["review_count"])
    except:
        restaurant_review_count.append(missing_api_result)
    try:
        restaurant_url.append(yelp_results[0]["url"])
    except:
        restaurant_url.append(missing_api_result)
    
    counter += 1

In [36]:
yelp_response

{'businesses': [],
 'total': 0,
 'region': {'center': {'longitude': -96.59557342529297,
   'latitude': 32.68127488496812}}}

In [45]:
# trying iterrows - need to add columns to existing dataframe to pass new data into


counter = 0

# yelp_response = []

# for restaurant in dallas_open_data_df_limited:
for row in dallas_open_data_df_limited["restaurant_name"]:
# for index, row in dallas_open_data_df_limited.iterrows():
    
    # get restaurant data from df and set as variable to pass through to API call
    # restaurant search variables
    search_name = dallas_open_data_df_limited["restaurant_name"][counter]
#     search_address = dallas_open_data_df_limited["street_address"][counter]
    search_street_number = dallas_open_data_df_limited["street_number"][counter]
    search_street_name = dallas_open_data_df_limited["street_name"][counter]
    search_zip_code = dallas_open_data_df_limited["zip_code"][counter]
    search_lat = dallas_open_data_df_limited["lat"][counter]
    search_lng = dallas_open_data_df_limited["long"][counter]
    
    # set parameters
    params = {"term": f"restaurant,{search_name}",
              "location": f"{search_street_number} {search_street_name}, {search_zip_code}",
#               "latitude": xx,
#               "longitude": xx,
              "radius": 100,
              "limit": 5
             }
    
    yelp_response = requests.get(url, params=params, headers=headers_1).json()
#     yelp_results = yelp_response["businesses"][0]
    yelp_results = yelp_response["businesses"]
    
    try:
        restaurant_category_test.append(yelp_results[0]["categories"][0]["title"])
    # not all results have > 1 category; in order to create dict, all lists must be same size - must assign "" when there is only one category
        if len(yelp_results[0]["categories"]) >= 1:
            restaurant_category_1.append(yelp_results[0]["categories"][0]["title"])
        else:
            restaurant_category_1.append(missing_api_result)
        if len(yelp_results[0]["categories"]) >= 2:
            restaurant_category_2.append(yelp_results[0]["categories"][1]["title"])
        else:
            restaurant_category_2.append(missing_api_result)
        if len(yelp_results[0]["categories"]) >= 3:
            restaurant_category_3.append(yelp_results[0]["categories"][2]["title"])
        else:
            restaurant_category_3.append(missing_api_result)
    except:
        restaurant_category_test.append(missing_api_result)
        
    try:
        restaurant_latitude.append(yelp_results[0]["coordinates"]["latitude"])
    except:
        restaurant_latitude.append(missing_api_result)
        
    try:
        restaurant_longitude.append(yelp_results[0]["coordinates"]["longitude"])
    except:
        restaurant_longitude.append(missing_api_result)
        
    try:
        restaurant_display_phone.append(yelp_results[0]["display_phone"])
    except:
        restaurant_display_phone.append(missing_api_result)
        
    try:
        restaurant_distance.append(yelp_results[0]["distance"])
    except:
        restaurant_distance.append(missing_api_result)
        
    try:
        restaurant_id.append(yelp_results[0]["id"])
    except:
        restaurant_id.append(missing_api_result)
        
    try:
        restaurant_alias.append(yelp_results[0]["alias"])
    except:
        restaurant_alias.append(missing_api_result)
        
    try:
        restaurant_image_url.append(yelp_results[0]["image_url"])
    except:
        restaurant_image_url.append(missing_api_result)
        
    try:
        restaurant_is_closed.append(yelp_results[0]["is_closed"])
    except:
        restaurant_is_closed.append(missing_api_result)
        
    try:
        restaurant_address1.append(yelp_results[0]["location"]["address1"])
    except:
        restaurant_address1.append(missing_api_result)
        
    try:
        restaurant_address2.append(yelp_results[0]["location"]["address2"])
    except:
        restaurant_address2.append(missing_api_result)
        
    try:
        restaurant_address3.append(yelp_results[0]["location"]["address3"])
    except:
        restaurant_address3.append(missing_api_result)
        
    try:
        restaurant_city.append(yelp_results[0]["location"]["city"])
    except:
        restaurant_city.append(missing_api_result)
        
    try:
        restaurant_country.append(yelp_results[0]["location"]["country"])
    except:
        restaurant_country.append(missing_api_result)
        
    try:
        restaurant_display_address.append(yelp_results[0]["location"]["display_address"])
    except:
        restaurant_display_address.append(missing_api_result)
        
    try:
        restaurant_state.append(yelp_results[0]["location"]["state"])
    except:
        restaurant_state.append(missing_api_result)
        
    try:
        restaurant_zip_code.append(yelp_results[0]["location"]["zip_code"])
    except:
        restaurant_zip_code.append(missing_api_result)
        
    try:
        restaurant_name.append(yelp_results[0]["name"])
    except:
        restaurant_name.append(missing_api_result)
        
    try:
        restaurant_phone.append(yelp_results[0]["phone"])
    except:
        restaurant_phone.append(missing_api_result)
        
#     restaurant_price.append(yelp_results[0]["price"])
    # not all results have Price; to prevent error, try/except error handling, assigning "", all lists must be same size - must assign "" when there is no Price
    try:
        restaurant_price.append(yelp_results[0]["price"])
    except:
        restaurant_price.append(missing_api_result)
    try:
        restaurant_rating.append(yelp_results[0]["rating"])
    except:
        restaurant_rating.append(missing_api_result)
    try:
        restaurant_review_count.append(yelp_results[0]["review_count"])
    except:
        restaurant_review_count.append(missing_api_result)
    try:
        restaurant_url.append(yelp_results[0]["url"])
    except:
        restaurant_url.append(missing_api_result)
    
    counter += 1

In [ ]:
restaurant_name

In [46]:
yelp_response

{'businesses': [],
 'total': 0,
 'region': {'center': {'longitude': -96.59557342529297,
   'latitude': 32.68127488496812}}}

In [ ]:
# create dictionary using the lists created from yelp_results json object
restaurant_dict = {"Name": restaurant_name,
#                    "Alias": restaurant_alias,
#                    "Category1": restaurant_category_1,
#                    "Category2": restaurant_category_2,
#                    "Category3": restaurant_category_3,
                   "Rating": restaurant_rating,
                   "ReviewCount": restaurant_review_count,
                   "Price": restaurant_price,
                   "Lat": restaurant_latitude,
                   "Lng": restaurant_longitude,
                   "Address": restaurant_address1,
                   "Address2": restaurant_address2,
#                    "Address3": restaurant_address3,
                   "City": restaurant_city,
                   "State": restaurant_state,
#                    "Country": restaurant_country,
                   "Zip": restaurant_zip_code,
#                    "DisplayAddress": restaurant_display_address,
                   "Phone": restaurant_phone,
#                    "DisplayPhone": restaurant_display_phone,
#                    "ImageURL": restaurant_image_url,
#                    "URL": restaurant_url
#                    "Transactions": restaurant_transactions,
                   "Closed?": restaurant_is_closed,
#                    "ID": restaurant_id,
                  }

In [ ]:
# visualize dictionary
# restaurant_dict

In [ ]:
# create data frame from dictionary 
restaurant_df = pd.DataFrame(restaurant_dict)

In [ ]:
# visualize data frame
restaurant_df.dropna()
restaurant_df

In [ ]:


# restaurant_df.to_csv(f"{output_data_filepath}yelp_test1.csv", encoding="utf-8", index=False)
restaurant_df.to_csv(f"{output_data_filepath}yelp_test1.csv", encoding="UTF-16LE", index=False)